{% set name = "ConservedWaterSearch" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ConservedWaterSearch-{{ version }}.tar.gz
  sha256: f07dedade40568d759d75120a752ac35a947da5b56b43d25e52abfae8c818776

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pymol-open-source
    - hdbscan
    - numpy
    - matplotlib-base
    - scikit-learn
    - nglview

test:
  imports:
    - ConservedWaterSearch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JecaTosovic/ConservedWaterSearch
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://ConservedWaterSearch.readthedocs.io/
  dev_url: https://github.com/JecaTosovic/ConservedWaterSearch
  summary: Determination of conserved waters from MD trajectories for drug design and materials science.

extra:
  recipe-maintainers:
    - JecaTosovic
    - DomFijan
