{% set name = "ConservedWaterSearch" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ConservedWaterSearch-{{ version }}.tar.gz
  sha256: 8ec66c449dab0c35f75be6bf381da00aff9f5ed5e3dc9ff30fe18c3af46d5182

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy >=1.22
    - scikit-learn >=1.3

test:
  imports:
    - ConservedWaterSearch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JecaTosovic/ConservedWaterSearch
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://ConservedWaterSearch.readthedocs.io/
  dev_url: https://github.com/JecaTosovic/ConservedWaterSearch
  summary: Determination of conserved waters from MD trajectories for drug design and materials science.

extra:
  recipe-maintainers:
    - JecaTosovic
    - DomFijan
